package main

import (
	"fmt"
	"os"

	"github.com/BurntSushi/toml"
)

// Config mirrors the bootstrap file produced by `akari node add`.
// The identity material is generated by the panel; the agent never talks to
// any port other than the panel's outbound gRPC endpoint.
type Config struct {
	PanelAddr  string         `toml:"panel_addr"`
	ServerName string         `toml:"server_name"`
	Identity   IdentityConfig `toml:"identity"`
}

type IdentityConfig struct {
	CAPEM   string `toml:"ca_pem"`
	CertPEM string `toml:"cert_pem"`
	KeyPEM  string `toml:"key_pem"`
}

func LoadConfig(path string) (*Config, error) {
	b, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("read config: %w", err)
	}
	var cfg Config
	if err := toml.Unmarshal(b, &cfg); err != nil {
		return nil, fmt.Errorf("parse config: %w", err)
	}
	if cfg.PanelAddr == "" {
		return nil, fmt.Errorf("panel_addr is required")
	}
	if cfg.Identity.CAPEM == "" || cfg.Identity.CertPEM == "" || cfg.Identity.KeyPEM == "" {
		return nil, fmt.Errorf("identity.ca_pem, identity.cert_pem and identity.key_pem are required")
	}
	if cfg.ServerName == "" {
		cfg.ServerName = cfg.PanelAddr
	}
	return &cfg, nil
}
