package main

import (
	"fmt"
	"os"

	"github.com/BurntSushi/toml"
)

// Config mirrors the bootstrap file produced by `akari node add`.
//
// v2 (M1-8): panel_addr, server_name, identity.ca_pem and a one-time
// enrollment_token; the agent generates its key locally and enrolls (the
// certificate and key then live in the state directory, identity.go).
// v1: identity.cert_pem + identity.key_pem generated by the panel; still
// accepted, and replaced by a locally generated key at the first renewal.
// The agent never talks to any port other than the panel's outbound gRPC
// endpoint.
type Config struct {
	PanelAddr       string         `toml:"panel_addr"`
	ServerName      string         `toml:"server_name"`
	EnrollmentToken string         `toml:"enrollment_token"`
	Identity        IdentityConfig `toml:"identity"`
}

type IdentityConfig struct {
	CAPEM   string `toml:"ca_pem"`
	CertPEM string `toml:"cert_pem"` // v1 only
	KeyPEM  string `toml:"key_pem"`  // v1 only
}

func LoadConfig(path string) (*Config, error) {
	b, err := os.ReadFile(path)
	if err != nil {
		return nil, fmt.Errorf("read config: %w", err)
	}
	var cfg Config
	md, err := toml.Decode(string(b), &cfg)
	if err != nil {
		return nil, fmt.Errorf("parse config: %w", err)
	}
	if un := md.Undecoded(); len(un) > 0 {
		return nil, fmt.Errorf("unknown config keys: %v", un)
	}
	if cfg.PanelAddr == "" {
		return nil, fmt.Errorf("panel_addr is required")
	}
	if cfg.Identity.CAPEM == "" {
		return nil, fmt.Errorf("identity.ca_pem is required")
	}
	if (cfg.Identity.CertPEM == "") != (cfg.Identity.KeyPEM == "") {
		return nil, fmt.Errorf("identity.cert_pem and identity.key_pem go together (v1 bootstrap file)")
	}
	if cfg.ServerName == "" {
		cfg.ServerName = cfg.PanelAddr
	}
	return &cfg, nil
}
