// Akari panel <-> agent control-plane contract.
//
// Transport: the agent dials OUT to the panel's gRPC port over TLS. The
// agent's client certificate is issued by the panel CA and identifies the
// node; no management port exists on the agent side.
//
// Client certificates are OPTIONAL at the TLS layer (a presented one must
// still verify against the panel CA) so that a fresh agent can reach
// AgentEnrollment.Enroll. Every AgentChannel method requires a verified
// client certificate and refuses the call (UNAUTHENTICATED) without one.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: agent.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentChannel_OpenChannel_FullMethodName   = "/akari.v1.AgentChannel/OpenChannel"
	AgentChannel_Renew_FullMethodName         = "/akari.v1.AgentChannel/Renew"
	AgentChannel_FetchArtifact_FullMethodName = "/akari.v1.AgentChannel/FetchArtifact"
)

// AgentChannelClient is the client API for AgentChannel service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Requires a verified client certificate on every method.
type AgentChannelClient interface {
	// Persistent bidirectional stream. The agent keeps it open for its whole
	// lifetime; the panel pushes config / user deltas on the same stream.
	OpenChannel(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentUp, PanelDown], error)
	// Certificate rotation (protocol >= 2). The caller is identified by its
	// client certificate; the CSR carries a NEW key (same rules as
	// EnrollRequest.csr_der). The panel records the new serial; the calling
	// certificate stays valid until the new one is first seen on a
	// connection (then it is revoked) or until it expires. Calling again with
	// the old certificate before the new one was seen replaces the unseen
	// one (it is revoked), so an agent that lost the answer simply retries.
	// Errors: UNAUTHENTICATED (no/unknown/revoked certificate),
	// FAILED_PRECONDITION (node being deleted), INVALID_ARGUMENT (bad CSR),
	// RESOURCE_EXHAUSTED (rate limited), UNAVAILABLE (retry later).
	Renew(ctx context.Context, in *RenewRequest, opts ...grpc.CallOption) (*IssuedCertificate, error)
	// Agent self-update artifact download (protocol >= 3, M6). Streams the
	// bytes of a release binary the panel holds, identified by its SHA-256
	// (from a signed manifest in an UpdateOffer), starting at `offset`
	// (resume). The panel only serves releases whose upload completed and
	// whose manifest verified; the AGENT verifies size, SHA-256 and the
	// manifest signature itself before using anything. Errors:
	// UNAUTHENTICATED (no/unknown/revoked certificate), NOT_FOUND (unknown
	// or incomplete artifact), INVALID_ARGUMENT (bad digest/offset),
	// RESOURCE_EXHAUSTED (too many concurrent downloads; retry later),
	// UNAVAILABLE (retry later).
	FetchArtifact(ctx context.Context, in *FetchArtifactRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ArtifactChunk], error)
}

type agentChannelClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentChannelClient(cc grpc.ClientConnInterface) AgentChannelClient {
	return &agentChannelClient{cc}
}

func (c *agentChannelClient) OpenChannel(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentUp, PanelDown], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentChannel_ServiceDesc.Streams[0], AgentChannel_OpenChannel_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AgentUp, PanelDown]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentChannel_OpenChannelClient = grpc.BidiStreamingClient[AgentUp, PanelDown]

func (c *agentChannelClient) Renew(ctx context.Context, in *RenewRequest, opts ...grpc.CallOption) (*IssuedCertificate, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IssuedCertificate)
	err := c.cc.Invoke(ctx, AgentChannel_Renew_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *agentChannelClient) FetchArtifact(ctx context.Context, in *FetchArtifactRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ArtifactChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentChannel_ServiceDesc.Streams[1], AgentChannel_FetchArtifact_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[FetchArtifactRequest, ArtifactChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentChannel_FetchArtifactClient = grpc.ServerStreamingClient[ArtifactChunk]

// AgentChannelServer is the server API for AgentChannel service.
// All implementations must embed UnimplementedAgentChannelServer
// for forward compatibility.
//
// Requires a verified client certificate on every method.
type AgentChannelServer interface {
	// Persistent bidirectional stream. The agent keeps it open for its whole
	// lifetime; the panel pushes config / user deltas on the same stream.
	OpenChannel(grpc.BidiStreamingServer[AgentUp, PanelDown]) error
	// Certificate rotation (protocol >= 2). The caller is identified by its
	// client certificate; the CSR carries a NEW key (same rules as
	// EnrollRequest.csr_der). The panel records the new serial; the calling
	// certificate stays valid until the new one is first seen on a
	// connection (then it is revoked) or until it expires. Calling again with
	// the old certificate before the new one was seen replaces the unseen
	// one (it is revoked), so an agent that lost the answer simply retries.
	// Errors: UNAUTHENTICATED (no/unknown/revoked certificate),
	// FAILED_PRECONDITION (node being deleted), INVALID_ARGUMENT (bad CSR),
	// RESOURCE_EXHAUSTED (rate limited), UNAVAILABLE (retry later).
	Renew(context.Context, *RenewRequest) (*IssuedCertificate, error)
	// Agent self-update artifact download (protocol >= 3, M6). Streams the
	// bytes of a release binary the panel holds, identified by its SHA-256
	// (from a signed manifest in an UpdateOffer), starting at `offset`
	// (resume). The panel only serves releases whose upload completed and
	// whose manifest verified; the AGENT verifies size, SHA-256 and the
	// manifest signature itself before using anything. Errors:
	// UNAUTHENTICATED (no/unknown/revoked certificate), NOT_FOUND (unknown
	// or incomplete artifact), INVALID_ARGUMENT (bad digest/offset),
	// RESOURCE_EXHAUSTED (too many concurrent downloads; retry later),
	// UNAVAILABLE (retry later).
	FetchArtifact(*FetchArtifactRequest, grpc.ServerStreamingServer[ArtifactChunk]) error
	mustEmbedUnimplementedAgentChannelServer()
}

// UnimplementedAgentChannelServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentChannelServer struct{}

func (UnimplementedAgentChannelServer) OpenChannel(grpc.BidiStreamingServer[AgentUp, PanelDown]) error {
	return status.Error(codes.Unimplemented, "method OpenChannel not implemented")
}
func (UnimplementedAgentChannelServer) Renew(context.Context, *RenewRequest) (*IssuedCertificate, error) {
	return nil, status.Error(codes.Unimplemented, "method Renew not implemented")
}
func (UnimplementedAgentChannelServer) FetchArtifact(*FetchArtifactRequest, grpc.ServerStreamingServer[ArtifactChunk]) error {
	return status.Error(codes.Unimplemented, "method FetchArtifact not implemented")
}
func (UnimplementedAgentChannelServer) mustEmbedUnimplementedAgentChannelServer() {}
func (UnimplementedAgentChannelServer) testEmbeddedByValue()                      {}

// UnsafeAgentChannelServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentChannelServer will
// result in compilation errors.
type UnsafeAgentChannelServer interface {
	mustEmbedUnimplementedAgentChannelServer()
}

func RegisterAgentChannelServer(s grpc.ServiceRegistrar, srv AgentChannelServer) {
	// If the following call panics, it indicates UnimplementedAgentChannelServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentChannel_ServiceDesc, srv)
}

func _AgentChannel_OpenChannel_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AgentChannelServer).OpenChannel(&grpc.GenericServerStream[AgentUp, PanelDown]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentChannel_OpenChannelServer = grpc.BidiStreamingServer[AgentUp, PanelDown]

func _AgentChannel_Renew_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentChannelServer).Renew(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentChannel_Renew_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentChannelServer).Renew(ctx, req.(*RenewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AgentChannel_FetchArtifact_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(FetchArtifactRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(AgentChannelServer).FetchArtifact(m, &grpc.GenericServerStream[FetchArtifactRequest, ArtifactChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentChannel_FetchArtifactServer = grpc.ServerStreamingServer[ArtifactChunk]

// AgentChannel_ServiceDesc is the grpc.ServiceDesc for AgentChannel service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentChannel_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "akari.v1.AgentChannel",
	HandlerType: (*AgentChannelServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Renew",
			Handler:    _AgentChannel_Renew_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "OpenChannel",
			Handler:       _AgentChannel_OpenChannel_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "FetchArtifact",
			Handler:       _AgentChannel_FetchArtifact_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "agent.proto",
}

const (
	AgentEnrollment_Enroll_FullMethodName = "/akari.v1.AgentEnrollment/Enroll"
)

// AgentEnrollmentClient is the client API for AgentEnrollment service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Callable WITHOUT a client certificate (server TLS is still verified by
// the agent against the CA from its bootstrap file).
type AgentEnrollmentClient interface {
	// Exchange a one-time enrollment token (from `akari node add` / the admin
	// API) and a CSR for the node's first client certificate. The token is
	// single use and expires (default 24h). Every token problem (unknown,
	// used, expired, node being deleted) is the same PERMISSION_DENIED
	// "enrollment refused". INVALID_ARGUMENT: bad CSR (checked before the
	// token, which stays unused). RESOURCE_EXHAUSTED: rate limited (per source
	// address and globally). UNAVAILABLE: retry later (token unused).
	Enroll(ctx context.Context, in *EnrollRequest, opts ...grpc.CallOption) (*IssuedCertificate, error)
}

type agentEnrollmentClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentEnrollmentClient(cc grpc.ClientConnInterface) AgentEnrollmentClient {
	return &agentEnrollmentClient{cc}
}

func (c *agentEnrollmentClient) Enroll(ctx context.Context, in *EnrollRequest, opts ...grpc.CallOption) (*IssuedCertificate, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IssuedCertificate)
	err := c.cc.Invoke(ctx, AgentEnrollment_Enroll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AgentEnrollmentServer is the server API for AgentEnrollment service.
// All implementations must embed UnimplementedAgentEnrollmentServer
// for forward compatibility.
//
// Callable WITHOUT a client certificate (server TLS is still verified by
// the agent against the CA from its bootstrap file).
type AgentEnrollmentServer interface {
	// Exchange a one-time enrollment token (from `akari node add` / the admin
	// API) and a CSR for the node's first client certificate. The token is
	// single use and expires (default 24h). Every token problem (unknown,
	// used, expired, node being deleted) is the same PERMISSION_DENIED
	// "enrollment refused". INVALID_ARGUMENT: bad CSR (checked before the
	// token, which stays unused). RESOURCE_EXHAUSTED: rate limited (per source
	// address and globally). UNAVAILABLE: retry later (token unused).
	Enroll(context.Context, *EnrollRequest) (*IssuedCertificate, error)
	mustEmbedUnimplementedAgentEnrollmentServer()
}

// UnimplementedAgentEnrollmentServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentEnrollmentServer struct{}

func (UnimplementedAgentEnrollmentServer) Enroll(context.Context, *EnrollRequest) (*IssuedCertificate, error) {
	return nil, status.Error(codes.Unimplemented, "method Enroll not implemented")
}
func (UnimplementedAgentEnrollmentServer) mustEmbedUnimplementedAgentEnrollmentServer() {}
func (UnimplementedAgentEnrollmentServer) testEmbeddedByValue()                         {}

// UnsafeAgentEnrollmentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentEnrollmentServer will
// result in compilation errors.
type UnsafeAgentEnrollmentServer interface {
	mustEmbedUnimplementedAgentEnrollmentServer()
}

func RegisterAgentEnrollmentServer(s grpc.ServiceRegistrar, srv AgentEnrollmentServer) {
	// If the following call panics, it indicates UnimplementedAgentEnrollmentServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentEnrollment_ServiceDesc, srv)
}

func _AgentEnrollment_Enroll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnrollRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AgentEnrollmentServer).Enroll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AgentEnrollment_Enroll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AgentEnrollmentServer).Enroll(ctx, req.(*EnrollRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AgentEnrollment_ServiceDesc is the grpc.ServiceDesc for AgentEnrollment service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentEnrollment_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "akari.v1.AgentEnrollment",
	HandlerType: (*AgentEnrollmentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Enroll",
			Handler:    _AgentEnrollment_Enroll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "agent.proto",
}
