// Akari panel <-> agent control-plane contract.
//
// Transport: the agent dials OUT to the panel over mutual TLS. The agent's
// client certificate is issued by the panel CA and identifies the node;
// no enrollment or management port exists on the agent side.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: agent.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AgentChannel_OpenChannel_FullMethodName = "/akari.v1.AgentChannel/OpenChannel"
)

// AgentChannelClient is the client API for AgentChannel service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AgentChannelClient interface {
	// Persistent bidirectional stream. The agent keeps it open for its whole
	// lifetime; the panel pushes config / user deltas on the same stream.
	OpenChannel(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentUp, PanelDown], error)
}

type agentChannelClient struct {
	cc grpc.ClientConnInterface
}

func NewAgentChannelClient(cc grpc.ClientConnInterface) AgentChannelClient {
	return &agentChannelClient{cc}
}

func (c *agentChannelClient) OpenChannel(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentUp, PanelDown], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &AgentChannel_ServiceDesc.Streams[0], AgentChannel_OpenChannel_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AgentUp, PanelDown]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentChannel_OpenChannelClient = grpc.BidiStreamingClient[AgentUp, PanelDown]

// AgentChannelServer is the server API for AgentChannel service.
// All implementations must embed UnimplementedAgentChannelServer
// for forward compatibility.
type AgentChannelServer interface {
	// Persistent bidirectional stream. The agent keeps it open for its whole
	// lifetime; the panel pushes config / user deltas on the same stream.
	OpenChannel(grpc.BidiStreamingServer[AgentUp, PanelDown]) error
	mustEmbedUnimplementedAgentChannelServer()
}

// UnimplementedAgentChannelServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAgentChannelServer struct{}

func (UnimplementedAgentChannelServer) OpenChannel(grpc.BidiStreamingServer[AgentUp, PanelDown]) error {
	return status.Error(codes.Unimplemented, "method OpenChannel not implemented")
}
func (UnimplementedAgentChannelServer) mustEmbedUnimplementedAgentChannelServer() {}
func (UnimplementedAgentChannelServer) testEmbeddedByValue()                      {}

// UnsafeAgentChannelServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AgentChannelServer will
// result in compilation errors.
type UnsafeAgentChannelServer interface {
	mustEmbedUnimplementedAgentChannelServer()
}

func RegisterAgentChannelServer(s grpc.ServiceRegistrar, srv AgentChannelServer) {
	// If the following call panics, it indicates UnimplementedAgentChannelServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AgentChannel_ServiceDesc, srv)
}

func _AgentChannel_OpenChannel_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AgentChannelServer).OpenChannel(&grpc.GenericServerStream[AgentUp, PanelDown]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type AgentChannel_OpenChannelServer = grpc.BidiStreamingServer[AgentUp, PanelDown]

// AgentChannel_ServiceDesc is the grpc.ServiceDesc for AgentChannel service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AgentChannel_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "akari.v1.AgentChannel",
	HandlerType: (*AgentChannelServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "OpenChannel",
			Handler:       _AgentChannel_OpenChannel_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "agent.proto",
}
