// Akari panel <-> agent control-plane contract.
//
// Transport: the agent dials OUT to the panel over mutual TLS. The agent's
// client certificate is issued by the panel CA and identifies the node;
// no enrollment or management port exists on the agent side.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: agent.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserOp_Op int32

const (
	UserOp_ADD    UserOp_Op = 0
	UserOp_REMOVE UserOp_Op = 1
)

// Enum value maps for UserOp_Op.
var (
	UserOp_Op_name = map[int32]string{
		0: "ADD",
		1: "REMOVE",
	}
	UserOp_Op_value = map[string]int32{
		"ADD":    0,
		"REMOVE": 1,
	}
)

func (x UserOp_Op) Enum() *UserOp_Op {
	p := new(UserOp_Op)
	*p = x
	return p
}

func (x UserOp_Op) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserOp_Op) Descriptor() protoreflect.EnumDescriptor {
	return file_agent_proto_enumTypes[0].Descriptor()
}

func (UserOp_Op) Type() protoreflect.EnumType {
	return &file_agent_proto_enumTypes[0]
}

func (x UserOp_Op) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserOp_Op.Descriptor instead.
func (UserOp_Op) EnumDescriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{8, 0}
}

type AgentInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentVersion  string                 `protobuf:"bytes,1,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	CoreVersion   string                 `protobuf:"bytes,2,opt,name=core_version,json=coreVersion,proto3" json:"core_version,omitempty"` // embedded xray-core version
	Os            string                 `protobuf:"bytes,3,opt,name=os,proto3" json:"os,omitempty"`
	Arch          string                 `protobuf:"bytes,4,opt,name=arch,proto3" json:"arch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentInfo) Reset() {
	*x = AgentInfo{}
	mi := &file_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentInfo) ProtoMessage() {}

func (x *AgentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentInfo.ProtoReflect.Descriptor instead.
func (*AgentInfo) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{0}
}

func (x *AgentInfo) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *AgentInfo) GetCoreVersion() string {
	if x != nil {
		return x.CoreVersion
	}
	return ""
}

func (x *AgentInfo) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *AgentInfo) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

// First message on every stream, and re-sent whenever the agent rebuilds
// its xray instance (traffic counters reset -> new session_id).
type Hello struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`              // fresh whenever traffic counters reset
	ConfigVersion uint64                 `protobuf:"varint,2,opt,name=config_version,json=configVersion,proto3" json:"config_version,omitempty"` // inbound config the agent currently holds
	UserVersion   uint64                 `protobuf:"varint,3,opt,name=user_version,json=userVersion,proto3" json:"user_version,omitempty"`       // user set the agent currently holds
	Info          *AgentInfo             `protobuf:"bytes,4,opt,name=info,proto3" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hello) Reset() {
	*x = Hello{}
	mi := &file_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{1}
}

func (x *Hello) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *Hello) GetConfigVersion() uint64 {
	if x != nil {
		return x.ConfigVersion
	}
	return 0
}

func (x *Hello) GetUserVersion() uint64 {
	if x != nil {
		return x.UserVersion
	}
	return 0
}

func (x *Hello) GetInfo() *AgentInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CpuPercent    float64                `protobuf:"fixed64,1,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`
	MemUsedBytes  uint64                 `protobuf:"varint,2,opt,name=mem_used_bytes,json=memUsedBytes,proto3" json:"mem_used_bytes,omitempty"`
	MemTotalBytes uint64                 `protobuf:"varint,3,opt,name=mem_total_bytes,json=memTotalBytes,proto3" json:"mem_total_bytes,omitempty"`
	Connections   uint64                 `protobuf:"varint,4,opt,name=connections,proto3" json:"connections,omitempty"`
	UptimeSeconds uint64                 `protobuf:"varint,5,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{2}
}

func (x *Heartbeat) GetCpuPercent() float64 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *Heartbeat) GetMemUsedBytes() uint64 {
	if x != nil {
		return x.MemUsedBytes
	}
	return 0
}

func (x *Heartbeat) GetMemTotalBytes() uint64 {
	if x != nil {
		return x.MemTotalBytes
	}
	return 0
}

func (x *Heartbeat) GetConnections() uint64 {
	if x != nil {
		return x.Connections
	}
	return 0
}

func (x *Heartbeat) GetUptimeSeconds() uint64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

type UserTraffic struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`     // panel user id; also the xray user "email" field
	UpBytes       uint64                 `protobuf:"varint,2,opt,name=up_bytes,json=upBytes,proto3" json:"up_bytes,omitempty"` // cumulative within the current session
	DownBytes     uint64                 `protobuf:"varint,3,opt,name=down_bytes,json=downBytes,proto3" json:"down_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserTraffic) Reset() {
	*x = UserTraffic{}
	mi := &file_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserTraffic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserTraffic) ProtoMessage() {}

func (x *UserTraffic) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserTraffic.ProtoReflect.Descriptor instead.
func (*UserTraffic) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{3}
}

func (x *UserTraffic) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserTraffic) GetUpBytes() uint64 {
	if x != nil {
		return x.UpBytes
	}
	return 0
}

func (x *UserTraffic) GetDownBytes() uint64 {
	if x != nil {
		return x.DownBytes
	}
	return 0
}

type TrafficReport struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Users       []*UserTraffic         `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	MonotonicMs uint64                 `protobuf:"varint,2,opt,name=monotonic_ms,json=monotonicMs,proto3" json:"monotonic_ms,omitempty"`
	// Session (xray instance lifetime) these counters belong to, read
	// atomically with them. The panel keys accounting on it and DROPS reports
	// without it (agents must be upgraded before the panel).
	SessionId     string `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrafficReport) Reset() {
	*x = TrafficReport{}
	mi := &file_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrafficReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrafficReport) ProtoMessage() {}

func (x *TrafficReport) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrafficReport.ProtoReflect.Descriptor instead.
func (*TrafficReport) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{4}
}

func (x *TrafficReport) GetUsers() []*UserTraffic {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *TrafficReport) GetMonotonicMs() uint64 {
	if x != nil {
		return x.MonotonicMs
	}
	return 0
}

func (x *TrafficReport) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

// Result of applying a Snapshot/Delta. Versions are the ATTEMPTED ones; on
// ok=false the agent keeps (and reports in Hello) its previous versions.
type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConfigVersion uint64                 `protobuf:"varint,1,opt,name=config_version,json=configVersion,proto3" json:"config_version,omitempty"`
	UserVersion   uint64                 `protobuf:"varint,2,opt,name=user_version,json=userVersion,proto3" json:"user_version,omitempty"`
	Ok            bool                   `protobuf:"varint,3,opt,name=ok,proto3" json:"ok,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{5}
}

func (x *Ack) GetConfigVersion() uint64 {
	if x != nil {
		return x.ConfigVersion
	}
	return 0
}

func (x *Ack) GetUserVersion() uint64 {
	if x != nil {
		return x.UserVersion
	}
	return 0
}

func (x *Ack) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *Ack) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type AgentUp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*AgentUp_Hello
	//	*AgentUp_Heartbeat
	//	*AgentUp_Traffic
	//	*AgentUp_Ack
	Msg           isAgentUp_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentUp) Reset() {
	*x = AgentUp{}
	mi := &file_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentUp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentUp) ProtoMessage() {}

func (x *AgentUp) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentUp.ProtoReflect.Descriptor instead.
func (*AgentUp) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{6}
}

func (x *AgentUp) GetMsg() isAgentUp_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *AgentUp) GetHello() *Hello {
	if x != nil {
		if x, ok := x.Msg.(*AgentUp_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *AgentUp) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Msg.(*AgentUp_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *AgentUp) GetTraffic() *TrafficReport {
	if x != nil {
		if x, ok := x.Msg.(*AgentUp_Traffic); ok {
			return x.Traffic
		}
	}
	return nil
}

func (x *AgentUp) GetAck() *Ack {
	if x != nil {
		if x, ok := x.Msg.(*AgentUp_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

type isAgentUp_Msg interface {
	isAgentUp_Msg()
}

type AgentUp_Hello struct {
	Hello *Hello `protobuf:"bytes,1,opt,name=hello,proto3,oneof"`
}

type AgentUp_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,2,opt,name=heartbeat,proto3,oneof"`
}

type AgentUp_Traffic struct {
	Traffic *TrafficReport `protobuf:"bytes,3,opt,name=traffic,proto3,oneof"`
}

type AgentUp_Ack struct {
	Ack *Ack `protobuf:"bytes,4,opt,name=ack,proto3,oneof"`
}

func (*AgentUp_Hello) isAgentUp_Msg() {}

func (*AgentUp_Heartbeat) isAgentUp_Msg() {}

func (*AgentUp_Traffic) isAgentUp_Msg() {}

func (*AgentUp_Ack) isAgentUp_Msg() {}

// One protocol account for one inbound. account_json follows the xray
// per-protocol account schema, e.g. {"id": "...", "flow": "xtls-rprx-vision"}
// for VLESS or {"password": "..."} for Trojan. protocol names the account
// type ("vless", "vmess", "trojan", "shadowsocks").
type InboundUser struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InboundTag    string                 `protobuf:"bytes,1,opt,name=inbound_tag,json=inboundTag,proto3" json:"inbound_tag,omitempty"`
	AccountJson   string                 `protobuf:"bytes,2,opt,name=account_json,json=accountJson,proto3" json:"account_json,omitempty"`
	Protocol      string                 `protobuf:"bytes,3,opt,name=protocol,proto3" json:"protocol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InboundUser) Reset() {
	*x = InboundUser{}
	mi := &file_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InboundUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InboundUser) ProtoMessage() {}

func (x *InboundUser) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InboundUser.ProtoReflect.Descriptor instead.
func (*InboundUser) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{7}
}

func (x *InboundUser) GetInboundTag() string {
	if x != nil {
		return x.InboundTag
	}
	return ""
}

func (x *InboundUser) GetAccountJson() string {
	if x != nil {
		return x.AccountJson
	}
	return ""
}

func (x *InboundUser) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

type UserOp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Op            UserOp_Op              `protobuf:"varint,1,opt,name=op,proto3,enum=akari.v1.UserOp_Op" json:"op,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	InboundUsers  []*InboundUser         `protobuf:"bytes,3,rep,name=inbound_users,json=inboundUsers,proto3" json:"inbound_users,omitempty"` // ignored for REMOVE
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserOp) Reset() {
	*x = UserOp{}
	mi := &file_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserOp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserOp) ProtoMessage() {}

func (x *UserOp) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserOp.ProtoReflect.Descriptor instead.
func (*UserOp) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{8}
}

func (x *UserOp) GetOp() UserOp_Op {
	if x != nil {
		return x.Op
	}
	return UserOp_ADD
}

func (x *UserOp) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserOp) GetInboundUsers() []*InboundUser {
	if x != nil {
		return x.InboundUsers
	}
	return nil
}

// Full desired state, sent when the agent's held versions mismatch the
// panel's. Contains the complete user set so the agent can converge from
// any state without a diff protocol.
type ConfigSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConfigVersion uint64                 `protobuf:"varint,1,opt,name=config_version,json=configVersion,proto3" json:"config_version,omitempty"`
	InboundsJson  string                 `protobuf:"bytes,2,opt,name=inbounds_json,json=inboundsJson,proto3" json:"inbounds_json,omitempty"` // xray "inbounds" array JSON
	UserVersion   uint64                 `protobuf:"varint,3,opt,name=user_version,json=userVersion,proto3" json:"user_version,omitempty"`
	Users         []*UserOp              `protobuf:"bytes,4,rep,name=users,proto3" json:"users,omitempty"` // complete desired user set
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigSnapshot) Reset() {
	*x = ConfigSnapshot{}
	mi := &file_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigSnapshot) ProtoMessage() {}

func (x *ConfigSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigSnapshot.ProtoReflect.Descriptor instead.
func (*ConfigSnapshot) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{9}
}

func (x *ConfigSnapshot) GetConfigVersion() uint64 {
	if x != nil {
		return x.ConfigVersion
	}
	return 0
}

func (x *ConfigSnapshot) GetInboundsJson() string {
	if x != nil {
		return x.InboundsJson
	}
	return ""
}

func (x *ConfigSnapshot) GetUserVersion() uint64 {
	if x != nil {
		return x.UserVersion
	}
	return 0
}

func (x *ConfigSnapshot) GetUsers() []*UserOp {
	if x != nil {
		return x.Users
	}
	return nil
}

type UserDelta struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserVersion   uint64                 `protobuf:"varint,1,opt,name=user_version,json=userVersion,proto3" json:"user_version,omitempty"` // version after applying all ops
	Ops           []*UserOp              `protobuf:"bytes,2,rep,name=ops,proto3" json:"ops,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserDelta) Reset() {
	*x = UserDelta{}
	mi := &file_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserDelta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserDelta) ProtoMessage() {}

func (x *UserDelta) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserDelta.ProtoReflect.Descriptor instead.
func (*UserDelta) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{10}
}

func (x *UserDelta) GetUserVersion() uint64 {
	if x != nil {
		return x.UserVersion
	}
	return 0
}

func (x *UserDelta) GetOps() []*UserOp {
	if x != nil {
		return x.Ops
	}
	return nil
}

type Noop struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Noop) Reset() {
	*x = Noop{}
	mi := &file_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Noop) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Noop) ProtoMessage() {}

func (x *Noop) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Noop.ProtoReflect.Descriptor instead.
func (*Noop) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{11}
}

type PanelDown struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*PanelDown_Snapshot
	//	*PanelDown_Delta
	//	*PanelDown_Noop
	Msg           isPanelDown_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PanelDown) Reset() {
	*x = PanelDown{}
	mi := &file_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PanelDown) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PanelDown) ProtoMessage() {}

func (x *PanelDown) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PanelDown.ProtoReflect.Descriptor instead.
func (*PanelDown) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{12}
}

func (x *PanelDown) GetMsg() isPanelDown_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *PanelDown) GetSnapshot() *ConfigSnapshot {
	if x != nil {
		if x, ok := x.Msg.(*PanelDown_Snapshot); ok {
			return x.Snapshot
		}
	}
	return nil
}

func (x *PanelDown) GetDelta() *UserDelta {
	if x != nil {
		if x, ok := x.Msg.(*PanelDown_Delta); ok {
			return x.Delta
		}
	}
	return nil
}

func (x *PanelDown) GetNoop() *Noop {
	if x != nil {
		if x, ok := x.Msg.(*PanelDown_Noop); ok {
			return x.Noop
		}
	}
	return nil
}

type isPanelDown_Msg interface {
	isPanelDown_Msg()
}

type PanelDown_Snapshot struct {
	Snapshot *ConfigSnapshot `protobuf:"bytes,1,opt,name=snapshot,proto3,oneof"`
}

type PanelDown_Delta struct {
	Delta *UserDelta `protobuf:"bytes,2,opt,name=delta,proto3,oneof"`
}

type PanelDown_Noop struct {
	Noop *Noop `protobuf:"bytes,3,opt,name=noop,proto3,oneof"`
}

func (*PanelDown_Snapshot) isPanelDown_Msg() {}

func (*PanelDown_Delta) isPanelDown_Msg() {}

func (*PanelDown_Noop) isPanelDown_Msg() {}

var File_agent_proto protoreflect.FileDescriptor

const file_agent_proto_rawDesc = "" +
	"\n" +
	"\vagent.proto\x12\bakari.v1\"w\n" +
	"\tAgentInfo\x12#\n" +
	"\ragent_version\x18\x01 \x01(\tR\fagentVersion\x12!\n" +
	"\fcore_version\x18\x02 \x01(\tR\vcoreVersion\x12\x0e\n" +
	"\x02os\x18\x03 \x01(\tR\x02os\x12\x12\n" +
	"\x04arch\x18\x04 \x01(\tR\x04arch\"\x99\x01\n" +
	"\x05Hello\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12%\n" +
	"\x0econfig_version\x18\x02 \x01(\x04R\rconfigVersion\x12!\n" +
	"\fuser_version\x18\x03 \x01(\x04R\vuserVersion\x12'\n" +
	"\x04info\x18\x04 \x01(\v2\x13.akari.v1.AgentInfoR\x04info\"\xc3\x01\n" +
	"\tHeartbeat\x12\x1f\n" +
	"\vcpu_percent\x18\x01 \x01(\x01R\n" +
	"cpuPercent\x12$\n" +
	"\x0emem_used_bytes\x18\x02 \x01(\x04R\fmemUsedBytes\x12&\n" +
	"\x0fmem_total_bytes\x18\x03 \x01(\x04R\rmemTotalBytes\x12 \n" +
	"\vconnections\x18\x04 \x01(\x04R\vconnections\x12%\n" +
	"\x0euptime_seconds\x18\x05 \x01(\x04R\ruptimeSeconds\"`\n" +
	"\vUserTraffic\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\bup_bytes\x18\x02 \x01(\x04R\aupBytes\x12\x1d\n" +
	"\n" +
	"down_bytes\x18\x03 \x01(\x04R\tdownBytes\"~\n" +
	"\rTrafficReport\x12+\n" +
	"\x05users\x18\x01 \x03(\v2\x15.akari.v1.UserTrafficR\x05users\x12!\n" +
	"\fmonotonic_ms\x18\x02 \x01(\x04R\vmonotonicMs\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\"u\n" +
	"\x03Ack\x12%\n" +
	"\x0econfig_version\x18\x01 \x01(\x04R\rconfigVersion\x12!\n" +
	"\fuser_version\x18\x02 \x01(\x04R\vuserVersion\x12\x0e\n" +
	"\x02ok\x18\x03 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"\xc6\x01\n" +
	"\aAgentUp\x12'\n" +
	"\x05hello\x18\x01 \x01(\v2\x0f.akari.v1.HelloH\x00R\x05hello\x123\n" +
	"\theartbeat\x18\x02 \x01(\v2\x13.akari.v1.HeartbeatH\x00R\theartbeat\x123\n" +
	"\atraffic\x18\x03 \x01(\v2\x17.akari.v1.TrafficReportH\x00R\atraffic\x12!\n" +
	"\x03ack\x18\x04 \x01(\v2\r.akari.v1.AckH\x00R\x03ackB\x05\n" +
	"\x03msg\"m\n" +
	"\vInboundUser\x12\x1f\n" +
	"\vinbound_tag\x18\x01 \x01(\tR\n" +
	"inboundTag\x12!\n" +
	"\faccount_json\x18\x02 \x01(\tR\vaccountJson\x12\x1a\n" +
	"\bprotocol\x18\x03 \x01(\tR\bprotocol\"\x9d\x01\n" +
	"\x06UserOp\x12#\n" +
	"\x02op\x18\x01 \x01(\x0e2\x13.akari.v1.UserOp.OpR\x02op\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12:\n" +
	"\rinbound_users\x18\x03 \x03(\v2\x15.akari.v1.InboundUserR\finboundUsers\"\x19\n" +
	"\x02Op\x12\a\n" +
	"\x03ADD\x10\x00\x12\n" +
	"\n" +
	"\x06REMOVE\x10\x01\"\xa7\x01\n" +
	"\x0eConfigSnapshot\x12%\n" +
	"\x0econfig_version\x18\x01 \x01(\x04R\rconfigVersion\x12#\n" +
	"\rinbounds_json\x18\x02 \x01(\tR\finboundsJson\x12!\n" +
	"\fuser_version\x18\x03 \x01(\x04R\vuserVersion\x12&\n" +
	"\x05users\x18\x04 \x03(\v2\x10.akari.v1.UserOpR\x05users\"R\n" +
	"\tUserDelta\x12!\n" +
	"\fuser_version\x18\x01 \x01(\x04R\vuserVersion\x12\"\n" +
	"\x03ops\x18\x02 \x03(\v2\x10.akari.v1.UserOpR\x03ops\"\x06\n" +
	"\x04Noop\"\x9d\x01\n" +
	"\tPanelDown\x126\n" +
	"\bsnapshot\x18\x01 \x01(\v2\x18.akari.v1.ConfigSnapshotH\x00R\bsnapshot\x12+\n" +
	"\x05delta\x18\x02 \x01(\v2\x13.akari.v1.UserDeltaH\x00R\x05delta\x12$\n" +
	"\x04noop\x18\x03 \x01(\v2\x0e.akari.v1.NoopH\x00R\x04noopB\x05\n" +
	"\x03msg2I\n" +
	"\fAgentChannel\x129\n" +
	"\vOpenChannel\x12\x11.akari.v1.AgentUp\x1a\x13.akari.v1.PanelDown(\x010\x01B\x10Z\x0eakari/agent/pbb\x06proto3"

var (
	file_agent_proto_rawDescOnce sync.Once
	file_agent_proto_rawDescData []byte
)

func file_agent_proto_rawDescGZIP() []byte {
	file_agent_proto_rawDescOnce.Do(func() {
		file_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_proto_rawDesc), len(file_agent_proto_rawDesc)))
	})
	return file_agent_proto_rawDescData
}

var file_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_agent_proto_goTypes = []any{
	(UserOp_Op)(0),         // 0: akari.v1.UserOp.Op
	(*AgentInfo)(nil),      // 1: akari.v1.AgentInfo
	(*Hello)(nil),          // 2: akari.v1.Hello
	(*Heartbeat)(nil),      // 3: akari.v1.Heartbeat
	(*UserTraffic)(nil),    // 4: akari.v1.UserTraffic
	(*TrafficReport)(nil),  // 5: akari.v1.TrafficReport
	(*Ack)(nil),            // 6: akari.v1.Ack
	(*AgentUp)(nil),        // 7: akari.v1.AgentUp
	(*InboundUser)(nil),    // 8: akari.v1.InboundUser
	(*UserOp)(nil),         // 9: akari.v1.UserOp
	(*ConfigSnapshot)(nil), // 10: akari.v1.ConfigSnapshot
	(*UserDelta)(nil),      // 11: akari.v1.UserDelta
	(*Noop)(nil),           // 12: akari.v1.Noop
	(*PanelDown)(nil),      // 13: akari.v1.PanelDown
}
var file_agent_proto_depIdxs = []int32{
	1,  // 0: akari.v1.Hello.info:type_name -> akari.v1.AgentInfo
	4,  // 1: akari.v1.TrafficReport.users:type_name -> akari.v1.UserTraffic
	2,  // 2: akari.v1.AgentUp.hello:type_name -> akari.v1.Hello
	3,  // 3: akari.v1.AgentUp.heartbeat:type_name -> akari.v1.Heartbeat
	5,  // 4: akari.v1.AgentUp.traffic:type_name -> akari.v1.TrafficReport
	6,  // 5: akari.v1.AgentUp.ack:type_name -> akari.v1.Ack
	0,  // 6: akari.v1.UserOp.op:type_name -> akari.v1.UserOp.Op
	8,  // 7: akari.v1.UserOp.inbound_users:type_name -> akari.v1.InboundUser
	9,  // 8: akari.v1.ConfigSnapshot.users:type_name -> akari.v1.UserOp
	9,  // 9: akari.v1.UserDelta.ops:type_name -> akari.v1.UserOp
	10, // 10: akari.v1.PanelDown.snapshot:type_name -> akari.v1.ConfigSnapshot
	11, // 11: akari.v1.PanelDown.delta:type_name -> akari.v1.UserDelta
	12, // 12: akari.v1.PanelDown.noop:type_name -> akari.v1.Noop
	7,  // 13: akari.v1.AgentChannel.OpenChannel:input_type -> akari.v1.AgentUp
	13, // 14: akari.v1.AgentChannel.OpenChannel:output_type -> akari.v1.PanelDown
	14, // [14:15] is the sub-list for method output_type
	13, // [13:14] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_agent_proto_init() }
func file_agent_proto_init() {
	if File_agent_proto != nil {
		return
	}
	file_agent_proto_msgTypes[6].OneofWrappers = []any{
		(*AgentUp_Hello)(nil),
		(*AgentUp_Heartbeat)(nil),
		(*AgentUp_Traffic)(nil),
		(*AgentUp_Ack)(nil),
	}
	file_agent_proto_msgTypes[12].OneofWrappers = []any{
		(*PanelDown_Snapshot)(nil),
		(*PanelDown_Delta)(nil),
		(*PanelDown_Noop)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_proto_rawDesc), len(file_agent_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_agent_proto_goTypes,
		DependencyIndexes: file_agent_proto_depIdxs,
		EnumInfos:         file_agent_proto_enumTypes,
		MessageInfos:      file_agent_proto_msgTypes,
	}.Build()
	File_agent_proto = out.File
	file_agent_proto_goTypes = nil
	file_agent_proto_depIdxs = nil
}
