// Akari panel <-> agent control-plane contract.
//
// Transport: the agent dials OUT to the panel's gRPC port over TLS. The
// agent's client certificate is issued by the panel CA and identifies the
// node; no management port exists on the agent side.
//
// Client certificates are OPTIONAL at the TLS layer (a presented one must
// still verify against the panel CA) so that a fresh agent can reach
// AgentEnrollment.Enroll. Every AgentChannel method requires a verified
// client certificate and refuses the call (UNAUTHENTICATED) without one.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: agent.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RemoveMode int32

const (
	// In place (UserDelta); the agent's gate dispatcher closes the user's
	// live connections.
	RemoveMode_REMOVE_MODE_GATE RemoveMode = 0
	// Fallback switch: any removal or credential change goes through a full
	// Snapshot (xray rebuild, drops every connection on the node). The panel
	// sends no such deltas; the agent also refuses them (BASE_MISMATCH).
	RemoveMode_REMOVE_MODE_REBUILD RemoveMode = 1
)

// Enum value maps for RemoveMode.
var (
	RemoveMode_name = map[int32]string{
		0: "REMOVE_MODE_GATE",
		1: "REMOVE_MODE_REBUILD",
	}
	RemoveMode_value = map[string]int32{
		"REMOVE_MODE_GATE":    0,
		"REMOVE_MODE_REBUILD": 1,
	}
)

func (x RemoveMode) Enum() *RemoveMode {
	p := new(RemoveMode)
	*p = x
	return p
}

func (x RemoveMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RemoveMode) Descriptor() protoreflect.EnumDescriptor {
	return file_agent_proto_enumTypes[0].Descriptor()
}

func (RemoveMode) Type() protoreflect.EnumType {
	return &file_agent_proto_enumTypes[0]
}

func (x RemoveMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RemoveMode.Descriptor instead.
func (RemoveMode) EnumDescriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{0}
}

type Ack_Reason int32

const (
	Ack_REASON_UNSPECIFIED Ack_Reason = 0 // protocol 0 agent: use `ok`
	Ack_REASON_OK          Ack_Reason = 1
	// The apply was attempted and failed (possibly partially). The panel
	// falls back to a Snapshot under its failure backoff.
	Ack_REASON_APPLY_FAILED Ack_Reason = 2
	// A UserDelta whose base is not what the agent holds (or the agent's
	// state is dirty after a failed delta). Nothing was changed; the panel
	// sends a Snapshot at once (not a failure, no backoff).
	Ack_REASON_BASE_MISMATCH Ack_Reason = 3
)

// Enum value maps for Ack_Reason.
var (
	Ack_Reason_name = map[int32]string{
		0: "REASON_UNSPECIFIED",
		1: "REASON_OK",
		2: "REASON_APPLY_FAILED",
		3: "REASON_BASE_MISMATCH",
	}
	Ack_Reason_value = map[string]int32{
		"REASON_UNSPECIFIED":   0,
		"REASON_OK":            1,
		"REASON_APPLY_FAILED":  2,
		"REASON_BASE_MISMATCH": 3,
	}
)

func (x Ack_Reason) Enum() *Ack_Reason {
	p := new(Ack_Reason)
	*p = x
	return p
}

func (x Ack_Reason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Ack_Reason) Descriptor() protoreflect.EnumDescriptor {
	return file_agent_proto_enumTypes[1].Descriptor()
}

func (Ack_Reason) Type() protoreflect.EnumType {
	return &file_agent_proto_enumTypes[1]
}

func (x Ack_Reason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Ack_Reason.Descriptor instead.
func (Ack_Reason) EnumDescriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{8, 0}
}

type UserOp_Op int32

const (
	UserOp_ADD    UserOp_Op = 0
	UserOp_REMOVE UserOp_Op = 1
)

// Enum value maps for UserOp_Op.
var (
	UserOp_Op_name = map[int32]string{
		0: "ADD",
		1: "REMOVE",
	}
	UserOp_Op_value = map[string]int32{
		"ADD":    0,
		"REMOVE": 1,
	}
)

func (x UserOp_Op) Enum() *UserOp_Op {
	p := new(UserOp_Op)
	*p = x
	return p
}

func (x UserOp_Op) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserOp_Op) Descriptor() protoreflect.EnumDescriptor {
	return file_agent_proto_enumTypes[2].Descriptor()
}

func (UserOp_Op) Type() protoreflect.EnumType {
	return &file_agent_proto_enumTypes[2]
}

func (x UserOp_Op) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserOp_Op.Descriptor instead.
func (UserOp_Op) EnumDescriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{11, 0}
}

type UpdateStatus_State int32

const (
	UpdateStatus_STATE_UNSPECIFIED UpdateStatus_State = 0
	// The offer failed a check (signature, platform, version policy,
	// panel protocol, already rolled back from); nothing was downloaded.
	UpdateStatus_STATE_REJECTED    UpdateStatus_State = 1
	UpdateStatus_STATE_DOWNLOADING UpdateStatus_State = 2
	// Download or verification failed, or the switch could not happen;
	// the running binary stays.
	UpdateStatus_STATE_FAILED UpdateStatus_State = 3
	// Verified and staged; final counters flushed; about to restart.
	UpdateStatus_STATE_RESTARTING UpdateStatus_State = 4
	// The new binary did not come up healthy (crashed on start, or no
	// connected + acked apply within the self-check timeout); the agent
	// went back to the previous binary. Sent by the binary that runs after
	// the rollback, after its Hello.
	UpdateStatus_STATE_ROLLED_BACK UpdateStatus_State = 5
	// The new binary passed its self-check (sent after its Hello + first
	// ok apply).
	UpdateStatus_STATE_CONFIRMED UpdateStatus_State = 6
)

// Enum value maps for UpdateStatus_State.
var (
	UpdateStatus_State_name = map[int32]string{
		0: "STATE_UNSPECIFIED",
		1: "STATE_REJECTED",
		2: "STATE_DOWNLOADING",
		3: "STATE_FAILED",
		4: "STATE_RESTARTING",
		5: "STATE_ROLLED_BACK",
		6: "STATE_CONFIRMED",
	}
	UpdateStatus_State_value = map[string]int32{
		"STATE_UNSPECIFIED": 0,
		"STATE_REJECTED":    1,
		"STATE_DOWNLOADING": 2,
		"STATE_FAILED":      3,
		"STATE_RESTARTING":  4,
		"STATE_ROLLED_BACK": 5,
		"STATE_CONFIRMED":   6,
	}
)

func (x UpdateStatus_State) Enum() *UpdateStatus_State {
	p := new(UpdateStatus_State)
	*p = x
	return p
}

func (x UpdateStatus_State) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UpdateStatus_State) Descriptor() protoreflect.EnumDescriptor {
	return file_agent_proto_enumTypes[3].Descriptor()
}

func (UpdateStatus_State) Type() protoreflect.EnumType {
	return &file_agent_proto_enumTypes[3]
}

func (x UpdateStatus_State) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UpdateStatus_State.Descriptor instead.
func (UpdateStatus_State) EnumDescriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{20, 0}
}

type EnrollRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Token string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	// PKCS#10 CSR (DER) for an ECDSA P-256 key generated on the node, signed
	// with ecdsa-with-SHA256. It must carry no attributes (no extension
	// request: no SANs, no key usages); the subject is ignored. The panel
	// decides every field of the certificate: subject CN=agent-<node id>,
	// ClientAuth only, a fresh random serial, its configured validity.
	CsrDer        []byte `protobuf:"bytes,2,opt,name=csr_der,json=csrDer,proto3" json:"csr_der,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrollRequest) Reset() {
	*x = EnrollRequest{}
	mi := &file_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollRequest) ProtoMessage() {}

func (x *EnrollRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollRequest.ProtoReflect.Descriptor instead.
func (*EnrollRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{0}
}

func (x *EnrollRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *EnrollRequest) GetCsrDer() []byte {
	if x != nil {
		return x.CsrDer
	}
	return nil
}

type RenewRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CsrDer        []byte                 `protobuf:"bytes,1,opt,name=csr_der,json=csrDer,proto3" json:"csr_der,omitempty"` // as EnrollRequest.csr_der, for a NEW key
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenewRequest) Reset() {
	*x = RenewRequest{}
	mi := &file_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenewRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenewRequest) ProtoMessage() {}

func (x *RenewRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenewRequest.ProtoReflect.Descriptor instead.
func (*RenewRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{1}
}

func (x *RenewRequest) GetCsrDer() []byte {
	if x != nil {
		return x.CsrDer
	}
	return nil
}

type IssuedCertificate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CertPem       string                 `protobuf:"bytes,1,opt,name=cert_pem,json=certPem,proto3" json:"cert_pem,omitempty"` // the node's client certificate (leaf only)
	CaPem         string                 `protobuf:"bytes,2,opt,name=ca_pem,json=caPem,proto3" json:"ca_pem,omitempty"`       // the panel CA that issued it
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssuedCertificate) Reset() {
	*x = IssuedCertificate{}
	mi := &file_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssuedCertificate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssuedCertificate) ProtoMessage() {}

func (x *IssuedCertificate) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssuedCertificate.ProtoReflect.Descriptor instead.
func (*IssuedCertificate) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{2}
}

func (x *IssuedCertificate) GetCertPem() string {
	if x != nil {
		return x.CertPem
	}
	return ""
}

func (x *IssuedCertificate) GetCaPem() string {
	if x != nil {
		return x.CaPem
	}
	return ""
}

type AgentInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentVersion  string                 `protobuf:"bytes,1,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	CoreVersion   string                 `protobuf:"bytes,2,opt,name=core_version,json=coreVersion,proto3" json:"core_version,omitempty"` // embedded xray-core version
	Os            string                 `protobuf:"bytes,3,opt,name=os,proto3" json:"os,omitempty"`
	Arch          string                 `protobuf:"bytes,4,opt,name=arch,proto3" json:"arch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentInfo) Reset() {
	*x = AgentInfo{}
	mi := &file_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentInfo) ProtoMessage() {}

func (x *AgentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentInfo.ProtoReflect.Descriptor instead.
func (*AgentInfo) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{3}
}

func (x *AgentInfo) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *AgentInfo) GetCoreVersion() string {
	if x != nil {
		return x.CoreVersion
	}
	return ""
}

func (x *AgentInfo) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *AgentInfo) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

// First message on every stream, and re-sent whenever the agent rebuilds
// its xray instance (traffic counters reset -> new session_id) or tears it
// down (lease expiry).
type Hello struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`              // fresh whenever traffic counters reset
	ConfigVersion uint64                 `protobuf:"varint,2,opt,name=config_version,json=configVersion,proto3" json:"config_version,omitempty"` // inbound config the agent currently holds
	UserVersion   uint64                 `protobuf:"varint,3,opt,name=user_version,json=userVersion,proto3" json:"user_version,omitempty"`       // user set the agent currently holds
	Info          *AgentInfo             `protobuf:"bytes,4,opt,name=info,proto3" json:"info,omitempty"`
	// Control-protocol revision the agent speaks. Agents that predate the
	// field send 0. The panel serves agents below its MIN_AGENT_PROTOCOL the
	// EMPTY desired state (no inbounds, no users) and never trusts their
	// Hello/Ack for convergence. Revisions:
	//   1 = UserDelta base/target + REPLACE semantics, Ack.reason/held_*,
	//       state_hash, LeaseGrant.
	//   2 = renews its certificate (AgentChannel.Renew). Protocol 1 agents
	//       are served as before; they just never rotate their certificate.
	//   3 = signed self-update (UpdateOffer, FetchArtifact, UpdateStatus).
	//       Protocol 1/2 agents are served as before; they are never
	//       offered an update.
	ProtocolVersion uint32 `protobuf:"varint,5,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	// State hash of what the agent actually runs (see "State hash" below),
	// for config_version + the applied user set. Empty for protocol 0.
	StateHash     string `protobuf:"bytes,6,opt,name=state_hash,json=stateHash,proto3" json:"state_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hello) Reset() {
	*x = Hello{}
	mi := &file_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{4}
}

func (x *Hello) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *Hello) GetConfigVersion() uint64 {
	if x != nil {
		return x.ConfigVersion
	}
	return 0
}

func (x *Hello) GetUserVersion() uint64 {
	if x != nil {
		return x.UserVersion
	}
	return 0
}

func (x *Hello) GetInfo() *AgentInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

func (x *Hello) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *Hello) GetStateHash() string {
	if x != nil {
		return x.StateHash
	}
	return ""
}

type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CpuPercent    float64                `protobuf:"fixed64,1,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`
	MemUsedBytes  uint64                 `protobuf:"varint,2,opt,name=mem_used_bytes,json=memUsedBytes,proto3" json:"mem_used_bytes,omitempty"`
	MemTotalBytes uint64                 `protobuf:"varint,3,opt,name=mem_total_bytes,json=memTotalBytes,proto3" json:"mem_total_bytes,omitempty"`
	// Proxied connections currently open through xray (the gate's tracked
	// dispatches; 0 when no instance runs).
	Connections uint64 `protobuf:"varint,4,opt,name=connections,proto3" json:"connections,omitempty"`
	// Seconds since the agent process started.
	UptimeSeconds uint64 `protobuf:"varint,5,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	// Seconds left on the fail-closed lease (see LeaseGrant); unset while no
	// lease is armed (no grant received since the agent started).
	LeaseRemainingSeconds *uint64 `protobuf:"varint,6,opt,name=lease_remaining_seconds,json=leaseRemainingSeconds,proto3,oneof" json:"lease_remaining_seconds,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{5}
}

func (x *Heartbeat) GetCpuPercent() float64 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *Heartbeat) GetMemUsedBytes() uint64 {
	if x != nil {
		return x.MemUsedBytes
	}
	return 0
}

func (x *Heartbeat) GetMemTotalBytes() uint64 {
	if x != nil {
		return x.MemTotalBytes
	}
	return 0
}

func (x *Heartbeat) GetConnections() uint64 {
	if x != nil {
		return x.Connections
	}
	return 0
}

func (x *Heartbeat) GetUptimeSeconds() uint64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *Heartbeat) GetLeaseRemainingSeconds() uint64 {
	if x != nil && x.LeaseRemainingSeconds != nil {
		return *x.LeaseRemainingSeconds
	}
	return 0
}

type UserTraffic struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`     // panel user id; also the xray user "email" field
	UpBytes       uint64                 `protobuf:"varint,2,opt,name=up_bytes,json=upBytes,proto3" json:"up_bytes,omitempty"` // cumulative within the current session
	DownBytes     uint64                 `protobuf:"varint,3,opt,name=down_bytes,json=downBytes,proto3" json:"down_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserTraffic) Reset() {
	*x = UserTraffic{}
	mi := &file_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserTraffic) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserTraffic) ProtoMessage() {}

func (x *UserTraffic) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserTraffic.ProtoReflect.Descriptor instead.
func (*UserTraffic) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{6}
}

func (x *UserTraffic) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserTraffic) GetUpBytes() uint64 {
	if x != nil {
		return x.UpBytes
	}
	return 0
}

func (x *UserTraffic) GetDownBytes() uint64 {
	if x != nil {
		return x.DownBytes
	}
	return 0
}

type TrafficReport struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	Users       []*UserTraffic         `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	MonotonicMs uint64                 `protobuf:"varint,2,opt,name=monotonic_ms,json=monotonicMs,proto3" json:"monotonic_ms,omitempty"`
	// Session (xray instance lifetime) these counters belong to, read
	// atomically with them. The panel keys accounting on it and DROPS reports
	// without it (agents must be upgraded before the panel).
	SessionId     string `protobuf:"bytes,3,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TrafficReport) Reset() {
	*x = TrafficReport{}
	mi := &file_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TrafficReport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrafficReport) ProtoMessage() {}

func (x *TrafficReport) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrafficReport.ProtoReflect.Descriptor instead.
func (*TrafficReport) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{7}
}

func (x *TrafficReport) GetUsers() []*UserTraffic {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *TrafficReport) GetMonotonicMs() uint64 {
	if x != nil {
		return x.MonotonicMs
	}
	return 0
}

func (x *TrafficReport) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

// Result of applying a Snapshot/Delta. Versions are the ATTEMPTED ones
// (the target); on ok=false the agent keeps (and reports in Hello) its
// previous versions.
type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConfigVersion uint64                 `protobuf:"varint,1,opt,name=config_version,json=configVersion,proto3" json:"config_version,omitempty"`
	UserVersion   uint64                 `protobuf:"varint,2,opt,name=user_version,json=userVersion,proto3" json:"user_version,omitempty"`
	Ok            bool                   `protobuf:"varint,3,opt,name=ok,proto3" json:"ok,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	Reason        Ack_Reason             `protobuf:"varint,5,opt,name=reason,proto3,enum=akari.v1.Ack_Reason" json:"reason,omitempty"` // protocol >= 1
	// What the agent holds AFTER handling the message (protocol >= 1).
	HeldConfigVersion uint64 `protobuf:"varint,6,opt,name=held_config_version,json=heldConfigVersion,proto3" json:"held_config_version,omitempty"`
	HeldUserVersion   uint64 `protobuf:"varint,7,opt,name=held_user_version,json=heldUserVersion,proto3" json:"held_user_version,omitempty"`
	// State hash of the held state (see Hello.state_hash).
	StateHash     string `protobuf:"bytes,8,opt,name=state_hash,json=stateHash,proto3" json:"state_hash,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{8}
}

func (x *Ack) GetConfigVersion() uint64 {
	if x != nil {
		return x.ConfigVersion
	}
	return 0
}

func (x *Ack) GetUserVersion() uint64 {
	if x != nil {
		return x.UserVersion
	}
	return 0
}

func (x *Ack) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *Ack) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *Ack) GetReason() Ack_Reason {
	if x != nil {
		return x.Reason
	}
	return Ack_REASON_UNSPECIFIED
}

func (x *Ack) GetHeldConfigVersion() uint64 {
	if x != nil {
		return x.HeldConfigVersion
	}
	return 0
}

func (x *Ack) GetHeldUserVersion() uint64 {
	if x != nil {
		return x.HeldUserVersion
	}
	return 0
}

func (x *Ack) GetStateHash() string {
	if x != nil {
		return x.StateHash
	}
	return ""
}

type AgentUp struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*AgentUp_Hello
	//	*AgentUp_Heartbeat
	//	*AgentUp_Traffic
	//	*AgentUp_Ack
	//	*AgentUp_UpdateStatus
	Msg           isAgentUp_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentUp) Reset() {
	*x = AgentUp{}
	mi := &file_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentUp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentUp) ProtoMessage() {}

func (x *AgentUp) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentUp.ProtoReflect.Descriptor instead.
func (*AgentUp) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{9}
}

func (x *AgentUp) GetMsg() isAgentUp_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *AgentUp) GetHello() *Hello {
	if x != nil {
		if x, ok := x.Msg.(*AgentUp_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *AgentUp) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Msg.(*AgentUp_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *AgentUp) GetTraffic() *TrafficReport {
	if x != nil {
		if x, ok := x.Msg.(*AgentUp_Traffic); ok {
			return x.Traffic
		}
	}
	return nil
}

func (x *AgentUp) GetAck() *Ack {
	if x != nil {
		if x, ok := x.Msg.(*AgentUp_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

func (x *AgentUp) GetUpdateStatus() *UpdateStatus {
	if x != nil {
		if x, ok := x.Msg.(*AgentUp_UpdateStatus); ok {
			return x.UpdateStatus
		}
	}
	return nil
}

type isAgentUp_Msg interface {
	isAgentUp_Msg()
}

type AgentUp_Hello struct {
	Hello *Hello `protobuf:"bytes,1,opt,name=hello,proto3,oneof"`
}

type AgentUp_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,2,opt,name=heartbeat,proto3,oneof"`
}

type AgentUp_Traffic struct {
	Traffic *TrafficReport `protobuf:"bytes,3,opt,name=traffic,proto3,oneof"`
}

type AgentUp_Ack struct {
	Ack *Ack `protobuf:"bytes,4,opt,name=ack,proto3,oneof"`
}

type AgentUp_UpdateStatus struct {
	UpdateStatus *UpdateStatus `protobuf:"bytes,5,opt,name=update_status,json=updateStatus,proto3,oneof"` // protocol >= 3
}

func (*AgentUp_Hello) isAgentUp_Msg() {}

func (*AgentUp_Heartbeat) isAgentUp_Msg() {}

func (*AgentUp_Traffic) isAgentUp_Msg() {}

func (*AgentUp_Ack) isAgentUp_Msg() {}

func (*AgentUp_UpdateStatus) isAgentUp_Msg() {}

// One protocol account for one inbound. account_json follows the xray
// per-protocol account schema, e.g. {"id": "...", "flow": "xtls-rprx-vision"}
// for VLESS or {"password": "..."} for Trojan. protocol names the account
// type ("vless", "vmess", "trojan", "shadowsocks").
type InboundUser struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InboundTag    string                 `protobuf:"bytes,1,opt,name=inbound_tag,json=inboundTag,proto3" json:"inbound_tag,omitempty"`
	AccountJson   string                 `protobuf:"bytes,2,opt,name=account_json,json=accountJson,proto3" json:"account_json,omitempty"`
	Protocol      string                 `protobuf:"bytes,3,opt,name=protocol,proto3" json:"protocol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InboundUser) Reset() {
	*x = InboundUser{}
	mi := &file_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InboundUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InboundUser) ProtoMessage() {}

func (x *InboundUser) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InboundUser.ProtoReflect.Descriptor instead.
func (*InboundUser) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{10}
}

func (x *InboundUser) GetInboundTag() string {
	if x != nil {
		return x.InboundTag
	}
	return ""
}

func (x *InboundUser) GetAccountJson() string {
	if x != nil {
		return x.AccountJson
	}
	return ""
}

func (x *InboundUser) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

// ADD has REPLACE semantics (protocol >= 1): the user ends up on EXACTLY
// the listed inbounds; tags not listed are removed, a changed account is
// swapped (and that user's live connections on the changed/removed tags are
// closed), an identical account is left untouched. REMOVE removes the user
// from every inbound and closes their live connections. Both are
// idempotent.
type UserOp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Op            UserOp_Op              `protobuf:"varint,1,opt,name=op,proto3,enum=akari.v1.UserOp_Op" json:"op,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	InboundUsers  []*InboundUser         `protobuf:"bytes,3,rep,name=inbound_users,json=inboundUsers,proto3" json:"inbound_users,omitempty"` // ignored for REMOVE
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserOp) Reset() {
	*x = UserOp{}
	mi := &file_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserOp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserOp) ProtoMessage() {}

func (x *UserOp) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserOp.ProtoReflect.Descriptor instead.
func (*UserOp) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{11}
}

func (x *UserOp) GetOp() UserOp_Op {
	if x != nil {
		return x.Op
	}
	return UserOp_ADD
}

func (x *UserOp) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UserOp) GetInboundUsers() []*InboundUser {
	if x != nil {
		return x.InboundUsers
	}
	return nil
}

// Full desired state, sent when the agent's held versions mismatch the
// panel's. Contains the complete user set so the agent can converge from
// any state without a diff protocol.
type ConfigSnapshot struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ConfigVersion uint64                 `protobuf:"varint,1,opt,name=config_version,json=configVersion,proto3" json:"config_version,omitempty"`
	InboundsJson  string                 `protobuf:"bytes,2,opt,name=inbounds_json,json=inboundsJson,proto3" json:"inbounds_json,omitempty"` // xray "inbounds" array JSON
	UserVersion   uint64                 `protobuf:"varint,3,opt,name=user_version,json=userVersion,proto3" json:"user_version,omitempty"`
	Users         []*UserOp              `protobuf:"bytes,4,rep,name=users,proto3" json:"users,omitempty"` // complete desired user set
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfigSnapshot) Reset() {
	*x = ConfigSnapshot{}
	mi := &file_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfigSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfigSnapshot) ProtoMessage() {}

func (x *ConfigSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfigSnapshot.ProtoReflect.Descriptor instead.
func (*ConfigSnapshot) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{12}
}

func (x *ConfigSnapshot) GetConfigVersion() uint64 {
	if x != nil {
		return x.ConfigVersion
	}
	return 0
}

func (x *ConfigSnapshot) GetInboundsJson() string {
	if x != nil {
		return x.InboundsJson
	}
	return ""
}

func (x *ConfigSnapshot) GetUserVersion() uint64 {
	if x != nil {
		return x.UserVersion
	}
	return 0
}

func (x *ConfigSnapshot) GetUsers() []*UserOp {
	if x != nil {
		return x.Users
	}
	return nil
}

// Incremental user-set change (protocol >= 1). Applies only on top of
// base: the agent applies it iff it holds exactly (base_config_version,
// base_user_version); if it already holds the target (config_version,
// user_version) it acks ok without changing anything (idempotent resend);
// otherwise it answers REASON_BASE_MISMATCH and keeps its state. A delta
// never changes inbounds: config_version == base_config_version. On a
// (partial) failure the agent keeps the base versions, marks its state
// dirty (further deltas get BASE_MISMATCH until a Snapshot) and its
// state_hash reflects what actually applied.
type UserDelta struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	UserVersion       uint64                 `protobuf:"varint,1,opt,name=user_version,json=userVersion,proto3" json:"user_version,omitempty"` // target user version, after applying all ops
	Ops               []*UserOp              `protobuf:"bytes,2,rep,name=ops,proto3" json:"ops,omitempty"`
	BaseConfigVersion uint64                 `protobuf:"varint,3,opt,name=base_config_version,json=baseConfigVersion,proto3" json:"base_config_version,omitempty"`
	BaseUserVersion   uint64                 `protobuf:"varint,4,opt,name=base_user_version,json=baseUserVersion,proto3" json:"base_user_version,omitempty"`
	ConfigVersion     uint64                 `protobuf:"varint,5,opt,name=config_version,json=configVersion,proto3" json:"config_version,omitempty"` // target config version == base_config_version
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UserDelta) Reset() {
	*x = UserDelta{}
	mi := &file_agent_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserDelta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserDelta) ProtoMessage() {}

func (x *UserDelta) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserDelta.ProtoReflect.Descriptor instead.
func (*UserDelta) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{13}
}

func (x *UserDelta) GetUserVersion() uint64 {
	if x != nil {
		return x.UserVersion
	}
	return 0
}

func (x *UserDelta) GetOps() []*UserOp {
	if x != nil {
		return x.Ops
	}
	return nil
}

func (x *UserDelta) GetBaseConfigVersion() uint64 {
	if x != nil {
		return x.BaseConfigVersion
	}
	return 0
}

func (x *UserDelta) GetBaseUserVersion() uint64 {
	if x != nil {
		return x.BaseUserVersion
	}
	return 0
}

func (x *UserDelta) GetConfigVersion() uint64 {
	if x != nil {
		return x.ConfigVersion
	}
	return 0
}

// Fail-closed lease (protocol >= 1). Sent only after the panel successfully
// read this node's desired state from its database for this stream
// (initial sync and every reconcile). The agent measures it on a clock that
// keeps running during suspend (CLOCK_BOOTTIME), accepts grants only from
// its current stream, treats 0 as the 24h default and clamps to >= 1h. On
// expiry it tears xray down, resets its held versions to (0,0) (next Hello
// forces a Snapshot) and keeps the final counters for the next stream.
type LeaseGrant struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	DurationSeconds uint64                 `protobuf:"varint,1,opt,name=duration_seconds,json=durationSeconds,proto3" json:"duration_seconds,omitempty"`
	// How user removals/rotations must be applied (panel config
	// agent.remove_mode). Carried on every grant, so it reaches the agent
	// with the first sync of each stream and before any Snapshot/UserDelta.
	RemoveMode    RemoveMode `protobuf:"varint,2,opt,name=remove_mode,json=removeMode,proto3,enum=akari.v1.RemoveMode" json:"remove_mode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaseGrant) Reset() {
	*x = LeaseGrant{}
	mi := &file_agent_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaseGrant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaseGrant) ProtoMessage() {}

func (x *LeaseGrant) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaseGrant.ProtoReflect.Descriptor instead.
func (*LeaseGrant) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{14}
}

func (x *LeaseGrant) GetDurationSeconds() uint64 {
	if x != nil {
		return x.DurationSeconds
	}
	return 0
}

func (x *LeaseGrant) GetRemoveMode() RemoveMode {
	if x != nil {
		return x.RemoveMode
	}
	return RemoveMode_REMOVE_MODE_GATE
}

type Noop struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Noop) Reset() {
	*x = Noop{}
	mi := &file_agent_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Noop) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Noop) ProtoMessage() {}

func (x *Noop) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Noop.ProtoReflect.Descriptor instead.
func (*Noop) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{15}
}

// --- Agent self-update (protocol >= 3, M6) --------------------------------
//
// Trust: the agent runs only binaries described by a manifest signed with
// an Ed25519 release key PINNED in the agent binary (never the panel's key,
// never a key the panel sends). The panel only relays: a compromised panel
// can withhold or delay updates, not push an unsigned, foreign-platform or
// downgraded binary.
//
// Manifest: UTF-8 JSON object, signed and transported VERBATIM (never
// re-serialized):
//
//	{"schema":1, "version":"v1.2.3", "os":"linux", "arch":"amd64",
//	 "sha256":"<64 lowercase hex>", "size":<bytes>,
//	 "min_panel_protocol":3, "created_at":"<RFC 3339>", "rollback":false}
//
// version is semver with a leading "v". The agent accepts it only if:
// some signature verifies under a pinned key; schema == 1; os/arch are its
// own; version > its running version (semver precedence) — or rollback is
// true (an explicitly signed rollback target), and never a version it
// already rolled back from; min_panel_protocol <= the offer's
// panel_protocol; size <= 256 MiB.
// Signature: Ed25519 over "akari-agent-manifest-v1\n" || manifest bytes.
// key_id: first 8 bytes of SHA-256(raw 32-byte public key), lowercase hex.
type ManifestSignature struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyId         string                 `protobuf:"bytes,1,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	Signature     []byte                 `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"` // 64 bytes
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ManifestSignature) Reset() {
	*x = ManifestSignature{}
	mi := &file_agent_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ManifestSignature) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ManifestSignature) ProtoMessage() {}

func (x *ManifestSignature) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ManifestSignature.ProtoReflect.Descriptor instead.
func (*ManifestSignature) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{16}
}

func (x *ManifestSignature) GetKeyId() string {
	if x != nil {
		return x.KeyId
	}
	return ""
}

func (x *ManifestSignature) GetSignature() []byte {
	if x != nil {
		return x.Signature
	}
	return nil
}

// Offer to update. Sent by the panel at most once per stream and rollout
// (re-sent on a new stream while the node's rollout entry is open). The
// agent answers with UpdateStatus (REJECTED on any check failure, else
// DOWNLOADING ... RESTARTING); a duplicate offer of the version it is
// already working on is ignored.
type UpdateOffer struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	RolloutId  string                 `protobuf:"bytes,1,opt,name=rollout_id,json=rolloutId,proto3" json:"rollout_id,omitempty"` // opaque, echoed in UpdateStatus
	Manifest   []byte                 `protobuf:"bytes,2,opt,name=manifest,proto3" json:"manifest,omitempty"`                    // the signed bytes, verbatim
	Signatures []*ManifestSignature   `protobuf:"bytes,3,rep,name=signatures,proto3" json:"signatures,omitempty"`                // any one valid suffices
	// The panel's control-protocol revision (the manifest's
	// min_panel_protocol must not exceed it).
	PanelProtocol uint32 `protobuf:"varint,4,opt,name=panel_protocol,json=panelProtocol,proto3" json:"panel_protocol,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateOffer) Reset() {
	*x = UpdateOffer{}
	mi := &file_agent_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateOffer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateOffer) ProtoMessage() {}

func (x *UpdateOffer) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateOffer.ProtoReflect.Descriptor instead.
func (*UpdateOffer) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{17}
}

func (x *UpdateOffer) GetRolloutId() string {
	if x != nil {
		return x.RolloutId
	}
	return ""
}

func (x *UpdateOffer) GetManifest() []byte {
	if x != nil {
		return x.Manifest
	}
	return nil
}

func (x *UpdateOffer) GetSignatures() []*ManifestSignature {
	if x != nil {
		return x.Signatures
	}
	return nil
}

func (x *UpdateOffer) GetPanelProtocol() uint32 {
	if x != nil {
		return x.PanelProtocol
	}
	return 0
}

type FetchArtifactRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sha256        string                 `protobuf:"bytes,1,opt,name=sha256,proto3" json:"sha256,omitempty"`  // lowercase hex, from the manifest
	Offset        uint64                 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"` // resume position; 0 = from the start
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchArtifactRequest) Reset() {
	*x = FetchArtifactRequest{}
	mi := &file_agent_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchArtifactRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchArtifactRequest) ProtoMessage() {}

func (x *FetchArtifactRequest) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchArtifactRequest.ProtoReflect.Descriptor instead.
func (*FetchArtifactRequest) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{18}
}

func (x *FetchArtifactRequest) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

func (x *FetchArtifactRequest) GetOffset() uint64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ArtifactChunk struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"` // consecutive bytes from the requested offset, <= 1 MiB
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArtifactChunk) Reset() {
	*x = ArtifactChunk{}
	mi := &file_agent_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArtifactChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArtifactChunk) ProtoMessage() {}

func (x *ArtifactChunk) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArtifactChunk.ProtoReflect.Descriptor instead.
func (*ArtifactChunk) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{19}
}

func (x *ArtifactChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// Progress / outcome of an update. Informational for the panel (its health
// gate is its own: a Hello with the new agent_version followed by an ok
// Ack within the rollout's timeout), except that REJECTED, FAILED and
// ROLLED_BACK mark the node failed at once.
type UpdateStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RolloutId     string                 `protobuf:"bytes,1,opt,name=rollout_id,json=rolloutId,proto3" json:"rollout_id,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"` // the offered / attempted version
	State         UpdateStatus_State     `protobuf:"varint,3,opt,name=state,proto3,enum=akari.v1.UpdateStatus_State" json:"state,omitempty"`
	Error         string                 `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStatus) Reset() {
	*x = UpdateStatus{}
	mi := &file_agent_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStatus) ProtoMessage() {}

func (x *UpdateStatus) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStatus.ProtoReflect.Descriptor instead.
func (*UpdateStatus) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{20}
}

func (x *UpdateStatus) GetRolloutId() string {
	if x != nil {
		return x.RolloutId
	}
	return ""
}

func (x *UpdateStatus) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *UpdateStatus) GetState() UpdateStatus_State {
	if x != nil {
		return x.State
	}
	return UpdateStatus_STATE_UNSPECIFIED
}

func (x *UpdateStatus) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type PanelDown struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Msg:
	//
	//	*PanelDown_Snapshot
	//	*PanelDown_Delta
	//	*PanelDown_Noop
	//	*PanelDown_Lease
	//	*PanelDown_UpdateOffer
	Msg           isPanelDown_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PanelDown) Reset() {
	*x = PanelDown{}
	mi := &file_agent_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PanelDown) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PanelDown) ProtoMessage() {}

func (x *PanelDown) ProtoReflect() protoreflect.Message {
	mi := &file_agent_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PanelDown.ProtoReflect.Descriptor instead.
func (*PanelDown) Descriptor() ([]byte, []int) {
	return file_agent_proto_rawDescGZIP(), []int{21}
}

func (x *PanelDown) GetMsg() isPanelDown_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *PanelDown) GetSnapshot() *ConfigSnapshot {
	if x != nil {
		if x, ok := x.Msg.(*PanelDown_Snapshot); ok {
			return x.Snapshot
		}
	}
	return nil
}

func (x *PanelDown) GetDelta() *UserDelta {
	if x != nil {
		if x, ok := x.Msg.(*PanelDown_Delta); ok {
			return x.Delta
		}
	}
	return nil
}

func (x *PanelDown) GetNoop() *Noop {
	if x != nil {
		if x, ok := x.Msg.(*PanelDown_Noop); ok {
			return x.Noop
		}
	}
	return nil
}

func (x *PanelDown) GetLease() *LeaseGrant {
	if x != nil {
		if x, ok := x.Msg.(*PanelDown_Lease); ok {
			return x.Lease
		}
	}
	return nil
}

func (x *PanelDown) GetUpdateOffer() *UpdateOffer {
	if x != nil {
		if x, ok := x.Msg.(*PanelDown_UpdateOffer); ok {
			return x.UpdateOffer
		}
	}
	return nil
}

type isPanelDown_Msg interface {
	isPanelDown_Msg()
}

type PanelDown_Snapshot struct {
	Snapshot *ConfigSnapshot `protobuf:"bytes,1,opt,name=snapshot,proto3,oneof"`
}

type PanelDown_Delta struct {
	Delta *UserDelta `protobuf:"bytes,2,opt,name=delta,proto3,oneof"`
}

type PanelDown_Noop struct {
	Noop *Noop `protobuf:"bytes,3,opt,name=noop,proto3,oneof"`
}

type PanelDown_Lease struct {
	Lease *LeaseGrant `protobuf:"bytes,4,opt,name=lease,proto3,oneof"`
}

type PanelDown_UpdateOffer struct {
	UpdateOffer *UpdateOffer `protobuf:"bytes,5,opt,name=update_offer,json=updateOffer,proto3,oneof"` // protocol >= 3
}

func (*PanelDown_Snapshot) isPanelDown_Msg() {}

func (*PanelDown_Delta) isPanelDown_Msg() {}

func (*PanelDown_Noop) isPanelDown_Msg() {}

func (*PanelDown_Lease) isPanelDown_Msg() {}

func (*PanelDown_UpdateOffer) isPanelDown_Msg() {}

var File_agent_proto protoreflect.FileDescriptor

const file_agent_proto_rawDesc = "" +
	"\n" +
	"\vagent.proto\x12\bakari.v1\">\n" +
	"\rEnrollRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x17\n" +
	"\acsr_der\x18\x02 \x01(\fR\x06csrDer\"'\n" +
	"\fRenewRequest\x12\x17\n" +
	"\acsr_der\x18\x01 \x01(\fR\x06csrDer\"E\n" +
	"\x11IssuedCertificate\x12\x19\n" +
	"\bcert_pem\x18\x01 \x01(\tR\acertPem\x12\x15\n" +
	"\x06ca_pem\x18\x02 \x01(\tR\x05caPem\"w\n" +
	"\tAgentInfo\x12#\n" +
	"\ragent_version\x18\x01 \x01(\tR\fagentVersion\x12!\n" +
	"\fcore_version\x18\x02 \x01(\tR\vcoreVersion\x12\x0e\n" +
	"\x02os\x18\x03 \x01(\tR\x02os\x12\x12\n" +
	"\x04arch\x18\x04 \x01(\tR\x04arch\"\xe3\x01\n" +
	"\x05Hello\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12%\n" +
	"\x0econfig_version\x18\x02 \x01(\x04R\rconfigVersion\x12!\n" +
	"\fuser_version\x18\x03 \x01(\x04R\vuserVersion\x12'\n" +
	"\x04info\x18\x04 \x01(\v2\x13.akari.v1.AgentInfoR\x04info\x12)\n" +
	"\x10protocol_version\x18\x05 \x01(\rR\x0fprotocolVersion\x12\x1d\n" +
	"\n" +
	"state_hash\x18\x06 \x01(\tR\tstateHash\"\x9c\x02\n" +
	"\tHeartbeat\x12\x1f\n" +
	"\vcpu_percent\x18\x01 \x01(\x01R\n" +
	"cpuPercent\x12$\n" +
	"\x0emem_used_bytes\x18\x02 \x01(\x04R\fmemUsedBytes\x12&\n" +
	"\x0fmem_total_bytes\x18\x03 \x01(\x04R\rmemTotalBytes\x12 \n" +
	"\vconnections\x18\x04 \x01(\x04R\vconnections\x12%\n" +
	"\x0euptime_seconds\x18\x05 \x01(\x04R\ruptimeSeconds\x12;\n" +
	"\x17lease_remaining_seconds\x18\x06 \x01(\x04H\x00R\x15leaseRemainingSeconds\x88\x01\x01B\x1a\n" +
	"\x18_lease_remaining_seconds\"`\n" +
	"\vUserTraffic\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\bup_bytes\x18\x02 \x01(\x04R\aupBytes\x12\x1d\n" +
	"\n" +
	"down_bytes\x18\x03 \x01(\x04R\tdownBytes\"~\n" +
	"\rTrafficReport\x12+\n" +
	"\x05users\x18\x01 \x03(\v2\x15.akari.v1.UserTrafficR\x05users\x12!\n" +
	"\fmonotonic_ms\x18\x02 \x01(\x04R\vmonotonicMs\x12\x1d\n" +
	"\n" +
	"session_id\x18\x03 \x01(\tR\tsessionId\"\x82\x03\n" +
	"\x03Ack\x12%\n" +
	"\x0econfig_version\x18\x01 \x01(\x04R\rconfigVersion\x12!\n" +
	"\fuser_version\x18\x02 \x01(\x04R\vuserVersion\x12\x0e\n" +
	"\x02ok\x18\x03 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\x12,\n" +
	"\x06reason\x18\x05 \x01(\x0e2\x14.akari.v1.Ack.ReasonR\x06reason\x12.\n" +
	"\x13held_config_version\x18\x06 \x01(\x04R\x11heldConfigVersion\x12*\n" +
	"\x11held_user_version\x18\a \x01(\x04R\x0fheldUserVersion\x12\x1d\n" +
	"\n" +
	"state_hash\x18\b \x01(\tR\tstateHash\"b\n" +
	"\x06Reason\x12\x16\n" +
	"\x12REASON_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tREASON_OK\x10\x01\x12\x17\n" +
	"\x13REASON_APPLY_FAILED\x10\x02\x12\x18\n" +
	"\x14REASON_BASE_MISMATCH\x10\x03\"\x85\x02\n" +
	"\aAgentUp\x12'\n" +
	"\x05hello\x18\x01 \x01(\v2\x0f.akari.v1.HelloH\x00R\x05hello\x123\n" +
	"\theartbeat\x18\x02 \x01(\v2\x13.akari.v1.HeartbeatH\x00R\theartbeat\x123\n" +
	"\atraffic\x18\x03 \x01(\v2\x17.akari.v1.TrafficReportH\x00R\atraffic\x12!\n" +
	"\x03ack\x18\x04 \x01(\v2\r.akari.v1.AckH\x00R\x03ack\x12=\n" +
	"\rupdate_status\x18\x05 \x01(\v2\x16.akari.v1.UpdateStatusH\x00R\fupdateStatusB\x05\n" +
	"\x03msg\"m\n" +
	"\vInboundUser\x12\x1f\n" +
	"\vinbound_tag\x18\x01 \x01(\tR\n" +
	"inboundTag\x12!\n" +
	"\faccount_json\x18\x02 \x01(\tR\vaccountJson\x12\x1a\n" +
	"\bprotocol\x18\x03 \x01(\tR\bprotocol\"\x9d\x01\n" +
	"\x06UserOp\x12#\n" +
	"\x02op\x18\x01 \x01(\x0e2\x13.akari.v1.UserOp.OpR\x02op\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12:\n" +
	"\rinbound_users\x18\x03 \x03(\v2\x15.akari.v1.InboundUserR\finboundUsers\"\x19\n" +
	"\x02Op\x12\a\n" +
	"\x03ADD\x10\x00\x12\n" +
	"\n" +
	"\x06REMOVE\x10\x01\"\xa7\x01\n" +
	"\x0eConfigSnapshot\x12%\n" +
	"\x0econfig_version\x18\x01 \x01(\x04R\rconfigVersion\x12#\n" +
	"\rinbounds_json\x18\x02 \x01(\tR\finboundsJson\x12!\n" +
	"\fuser_version\x18\x03 \x01(\x04R\vuserVersion\x12&\n" +
	"\x05users\x18\x04 \x03(\v2\x10.akari.v1.UserOpR\x05users\"\xd5\x01\n" +
	"\tUserDelta\x12!\n" +
	"\fuser_version\x18\x01 \x01(\x04R\vuserVersion\x12\"\n" +
	"\x03ops\x18\x02 \x03(\v2\x10.akari.v1.UserOpR\x03ops\x12.\n" +
	"\x13base_config_version\x18\x03 \x01(\x04R\x11baseConfigVersion\x12*\n" +
	"\x11base_user_version\x18\x04 \x01(\x04R\x0fbaseUserVersion\x12%\n" +
	"\x0econfig_version\x18\x05 \x01(\x04R\rconfigVersion\"n\n" +
	"\n" +
	"LeaseGrant\x12)\n" +
	"\x10duration_seconds\x18\x01 \x01(\x04R\x0fdurationSeconds\x125\n" +
	"\vremove_mode\x18\x02 \x01(\x0e2\x14.akari.v1.RemoveModeR\n" +
	"removeMode\"\x06\n" +
	"\x04Noop\"H\n" +
	"\x11ManifestSignature\x12\x15\n" +
	"\x06key_id\x18\x01 \x01(\tR\x05keyId\x12\x1c\n" +
	"\tsignature\x18\x02 \x01(\fR\tsignature\"\xac\x01\n" +
	"\vUpdateOffer\x12\x1d\n" +
	"\n" +
	"rollout_id\x18\x01 \x01(\tR\trolloutId\x12\x1a\n" +
	"\bmanifest\x18\x02 \x01(\fR\bmanifest\x12;\n" +
	"\n" +
	"signatures\x18\x03 \x03(\v2\x1b.akari.v1.ManifestSignatureR\n" +
	"signatures\x12%\n" +
	"\x0epanel_protocol\x18\x04 \x01(\rR\rpanelProtocol\"F\n" +
	"\x14FetchArtifactRequest\x12\x16\n" +
	"\x06sha256\x18\x01 \x01(\tR\x06sha256\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x04R\x06offset\"#\n" +
	"\rArtifactChunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"\xb1\x02\n" +
	"\fUpdateStatus\x12\x1d\n" +
	"\n" +
	"rollout_id\x18\x01 \x01(\tR\trolloutId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x122\n" +
	"\x05state\x18\x03 \x01(\x0e2\x1c.akari.v1.UpdateStatus.StateR\x05state\x12\x14\n" +
	"\x05error\x18\x04 \x01(\tR\x05error\"\x9d\x01\n" +
	"\x05State\x12\x15\n" +
	"\x11STATE_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eSTATE_REJECTED\x10\x01\x12\x15\n" +
	"\x11STATE_DOWNLOADING\x10\x02\x12\x10\n" +
	"\fSTATE_FAILED\x10\x03\x12\x14\n" +
	"\x10STATE_RESTARTING\x10\x04\x12\x15\n" +
	"\x11STATE_ROLLED_BACK\x10\x05\x12\x13\n" +
	"\x0fSTATE_CONFIRMED\x10\x06\"\x87\x02\n" +
	"\tPanelDown\x126\n" +
	"\bsnapshot\x18\x01 \x01(\v2\x18.akari.v1.ConfigSnapshotH\x00R\bsnapshot\x12+\n" +
	"\x05delta\x18\x02 \x01(\v2\x13.akari.v1.UserDeltaH\x00R\x05delta\x12$\n" +
	"\x04noop\x18\x03 \x01(\v2\x0e.akari.v1.NoopH\x00R\x04noop\x12,\n" +
	"\x05lease\x18\x04 \x01(\v2\x14.akari.v1.LeaseGrantH\x00R\x05lease\x12:\n" +
	"\fupdate_offer\x18\x05 \x01(\v2\x15.akari.v1.UpdateOfferH\x00R\vupdateOfferB\x05\n" +
	"\x03msg*;\n" +
	"\n" +
	"RemoveMode\x12\x14\n" +
	"\x10REMOVE_MODE_GATE\x10\x00\x12\x17\n" +
	"\x13REMOVE_MODE_REBUILD\x10\x012\xd3\x01\n" +
	"\fAgentChannel\x129\n" +
	"\vOpenChannel\x12\x11.akari.v1.AgentUp\x1a\x13.akari.v1.PanelDown(\x010\x01\x12<\n" +
	"\x05Renew\x12\x16.akari.v1.RenewRequest\x1a\x1b.akari.v1.IssuedCertificate\x12J\n" +
	"\rFetchArtifact\x12\x1e.akari.v1.FetchArtifactRequest\x1a\x17.akari.v1.ArtifactChunk0\x012Q\n" +
	"\x0fAgentEnrollment\x12>\n" +
	"\x06Enroll\x12\x17.akari.v1.EnrollRequest\x1a\x1b.akari.v1.IssuedCertificateB\x10Z\x0eakari/agent/pbb\x06proto3"

var (
	file_agent_proto_rawDescOnce sync.Once
	file_agent_proto_rawDescData []byte
)

func file_agent_proto_rawDescGZIP() []byte {
	file_agent_proto_rawDescOnce.Do(func() {
		file_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_agent_proto_rawDesc), len(file_agent_proto_rawDesc)))
	})
	return file_agent_proto_rawDescData
}

var file_agent_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_agent_proto_goTypes = []any{
	(RemoveMode)(0),              // 0: akari.v1.RemoveMode
	(Ack_Reason)(0),              // 1: akari.v1.Ack.Reason
	(UserOp_Op)(0),               // 2: akari.v1.UserOp.Op
	(UpdateStatus_State)(0),      // 3: akari.v1.UpdateStatus.State
	(*EnrollRequest)(nil),        // 4: akari.v1.EnrollRequest
	(*RenewRequest)(nil),         // 5: akari.v1.RenewRequest
	(*IssuedCertificate)(nil),    // 6: akari.v1.IssuedCertificate
	(*AgentInfo)(nil),            // 7: akari.v1.AgentInfo
	(*Hello)(nil),                // 8: akari.v1.Hello
	(*Heartbeat)(nil),            // 9: akari.v1.Heartbeat
	(*UserTraffic)(nil),          // 10: akari.v1.UserTraffic
	(*TrafficReport)(nil),        // 11: akari.v1.TrafficReport
	(*Ack)(nil),                  // 12: akari.v1.Ack
	(*AgentUp)(nil),              // 13: akari.v1.AgentUp
	(*InboundUser)(nil),          // 14: akari.v1.InboundUser
	(*UserOp)(nil),               // 15: akari.v1.UserOp
	(*ConfigSnapshot)(nil),       // 16: akari.v1.ConfigSnapshot
	(*UserDelta)(nil),            // 17: akari.v1.UserDelta
	(*LeaseGrant)(nil),           // 18: akari.v1.LeaseGrant
	(*Noop)(nil),                 // 19: akari.v1.Noop
	(*ManifestSignature)(nil),    // 20: akari.v1.ManifestSignature
	(*UpdateOffer)(nil),          // 21: akari.v1.UpdateOffer
	(*FetchArtifactRequest)(nil), // 22: akari.v1.FetchArtifactRequest
	(*ArtifactChunk)(nil),        // 23: akari.v1.ArtifactChunk
	(*UpdateStatus)(nil),         // 24: akari.v1.UpdateStatus
	(*PanelDown)(nil),            // 25: akari.v1.PanelDown
}
var file_agent_proto_depIdxs = []int32{
	7,  // 0: akari.v1.Hello.info:type_name -> akari.v1.AgentInfo
	10, // 1: akari.v1.TrafficReport.users:type_name -> akari.v1.UserTraffic
	1,  // 2: akari.v1.Ack.reason:type_name -> akari.v1.Ack.Reason
	8,  // 3: akari.v1.AgentUp.hello:type_name -> akari.v1.Hello
	9,  // 4: akari.v1.AgentUp.heartbeat:type_name -> akari.v1.Heartbeat
	11, // 5: akari.v1.AgentUp.traffic:type_name -> akari.v1.TrafficReport
	12, // 6: akari.v1.AgentUp.ack:type_name -> akari.v1.Ack
	24, // 7: akari.v1.AgentUp.update_status:type_name -> akari.v1.UpdateStatus
	2,  // 8: akari.v1.UserOp.op:type_name -> akari.v1.UserOp.Op
	14, // 9: akari.v1.UserOp.inbound_users:type_name -> akari.v1.InboundUser
	15, // 10: akari.v1.ConfigSnapshot.users:type_name -> akari.v1.UserOp
	15, // 11: akari.v1.UserDelta.ops:type_name -> akari.v1.UserOp
	0,  // 12: akari.v1.LeaseGrant.remove_mode:type_name -> akari.v1.RemoveMode
	20, // 13: akari.v1.UpdateOffer.signatures:type_name -> akari.v1.ManifestSignature
	3,  // 14: akari.v1.UpdateStatus.state:type_name -> akari.v1.UpdateStatus.State
	16, // 15: akari.v1.PanelDown.snapshot:type_name -> akari.v1.ConfigSnapshot
	17, // 16: akari.v1.PanelDown.delta:type_name -> akari.v1.UserDelta
	19, // 17: akari.v1.PanelDown.noop:type_name -> akari.v1.Noop
	18, // 18: akari.v1.PanelDown.lease:type_name -> akari.v1.LeaseGrant
	21, // 19: akari.v1.PanelDown.update_offer:type_name -> akari.v1.UpdateOffer
	13, // 20: akari.v1.AgentChannel.OpenChannel:input_type -> akari.v1.AgentUp
	5,  // 21: akari.v1.AgentChannel.Renew:input_type -> akari.v1.RenewRequest
	22, // 22: akari.v1.AgentChannel.FetchArtifact:input_type -> akari.v1.FetchArtifactRequest
	4,  // 23: akari.v1.AgentEnrollment.Enroll:input_type -> akari.v1.EnrollRequest
	25, // 24: akari.v1.AgentChannel.OpenChannel:output_type -> akari.v1.PanelDown
	6,  // 25: akari.v1.AgentChannel.Renew:output_type -> akari.v1.IssuedCertificate
	23, // 26: akari.v1.AgentChannel.FetchArtifact:output_type -> akari.v1.ArtifactChunk
	6,  // 27: akari.v1.AgentEnrollment.Enroll:output_type -> akari.v1.IssuedCertificate
	24, // [24:28] is the sub-list for method output_type
	20, // [20:24] is the sub-list for method input_type
	20, // [20:20] is the sub-list for extension type_name
	20, // [20:20] is the sub-list for extension extendee
	0,  // [0:20] is the sub-list for field type_name
}

func init() { file_agent_proto_init() }
func file_agent_proto_init() {
	if File_agent_proto != nil {
		return
	}
	file_agent_proto_msgTypes[5].OneofWrappers = []any{}
	file_agent_proto_msgTypes[9].OneofWrappers = []any{
		(*AgentUp_Hello)(nil),
		(*AgentUp_Heartbeat)(nil),
		(*AgentUp_Traffic)(nil),
		(*AgentUp_Ack)(nil),
		(*AgentUp_UpdateStatus)(nil),
	}
	file_agent_proto_msgTypes[21].OneofWrappers = []any{
		(*PanelDown_Snapshot)(nil),
		(*PanelDown_Delta)(nil),
		(*PanelDown_Noop)(nil),
		(*PanelDown_Lease)(nil),
		(*PanelDown_UpdateOffer)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_agent_proto_rawDesc), len(file_agent_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_agent_proto_goTypes,
		DependencyIndexes: file_agent_proto_depIdxs,
		EnumInfos:         file_agent_proto_enumTypes,
		MessageInfos:      file_agent_proto_msgTypes,
	}.Build()
	File_agent_proto = out.File
	file_agent_proto_goTypes = nil
	file_agent_proto_depIdxs = nil
}
