// Agent-internal (NOT part of the panel contract, not vendored): the xray
// app config that installs the agent's gate dispatcher (gate.go) in place of
// xray's DefaultDispatcher. xray instantiates apps from typed proto
// messages, so the gate needs a message type of its own.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: gate.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GateDispatcherConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GateDispatcherConfig) Reset() {
	*x = GateDispatcherConfig{}
	mi := &file_gate_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GateDispatcherConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GateDispatcherConfig) ProtoMessage() {}

func (x *GateDispatcherConfig) ProtoReflect() protoreflect.Message {
	mi := &file_gate_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GateDispatcherConfig.ProtoReflect.Descriptor instead.
func (*GateDispatcherConfig) Descriptor() ([]byte, []int) {
	return file_gate_proto_rawDescGZIP(), []int{0}
}

var File_gate_proto protoreflect.FileDescriptor

const file_gate_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"gate.proto\x12\x0eakari.agent.v1\"\x16\n" +
	"\x14GateDispatcherConfigB\x10Z\x0eakari/agent/pbb\x06proto3"

var (
	file_gate_proto_rawDescOnce sync.Once
	file_gate_proto_rawDescData []byte
)

func file_gate_proto_rawDescGZIP() []byte {
	file_gate_proto_rawDescOnce.Do(func() {
		file_gate_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_gate_proto_rawDesc), len(file_gate_proto_rawDesc)))
	})
	return file_gate_proto_rawDescData
}

var file_gate_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_gate_proto_goTypes = []any{
	(*GateDispatcherConfig)(nil), // 0: akari.agent.v1.GateDispatcherConfig
}
var file_gate_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_gate_proto_init() }
func file_gate_proto_init() {
	if File_gate_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_gate_proto_rawDesc), len(file_gate_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_gate_proto_goTypes,
		DependencyIndexes: file_gate_proto_depIdxs,
		MessageInfos:      file_gate_proto_msgTypes,
	}.Build()
	File_gate_proto = out.File
	file_gate_proto_goTypes = nil
	file_gate_proto_depIdxs = nil
}
